### ISSUE TITLE
[Chains] implement and fix `chains update`

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris#707] opened 2016-05-12 20:59 UTC
had a running chain, ran eris chains update (which should allow me to save the data container, pull the image, and restart it). Post update I had a wrong key error with this information:

```
Getting Public Key                       from=http://keys:4767
                                      defAddr=C610A068E4B07665936E4462862E3BA74A524991

Unfortunately the marmots could not find the key you are trying to use in the keys service.

There are two ways to fix this.
  1. Import your keys from your host: eris keys import C610A068E4B07665936E4462862E3BA74A524991
  2. Import your keys from your chain:

eris chains exec tendermint_testnet_11 "mintkey eris chains/tendermint_testnet_11/priv_validator.json" && \
eris services exec keys "chown eris:eris -R /home/eris"

Now, run  eris keys ls  to check that the keys are available. If they are not there
then change the account. Once you have verified that the keys for account

C610A068E4B07665936E4462862E3BA74A524991

are in the keys service, then rerun me.
```

that exec is formulated by epm, but this error lies in chains or in the base images (relates to -> https://github.com/eris-ltd/eris-cm/issues/5 and @benjaminbollen 's efforts to DRY up our configs). What's happening is the chain is reporting it's chain_id to epm and then epm is formulating that command using the chain_id. That is (oddly; still) the default chain_id we give to the image (I'm pretty sure).

@benjaminbollen I'm going to assign you this issue since you're working in the area of cleaning this all up.

**Comment by slowtokyo** [comment] 2016-05-13 14:50
+1

**Comment by compleatang** [comment] 2016-08-22 12:43
@benjaminbollen and @pietv ping on this issue. it also relates to another issue which I'll need to find.

**Comment by zramsay** [comment] 2016-09-14 07:22
`chains update` has been commented out FTTB. bumping to future release

**Comment by zramsay** [comment] 2017-02-02 15:54
duplicate of #1010, which is tagged an an Epic

**Closed by zramsay** 2017-02-02 15:54 UTC
Labels: bug/confirmed, triaged
